### ISSUE TITLE
Testes da TDA Stack

### ISSUE THREAD

**Issue by raphaelramosds** [eduardolfalcao/edi#7]
Um dos testes dessa TDA está implementado de forma errada. Segue a implementação feita

```go
func TestPop(t *testing.T) {
	defer setupTest()()
	for _, stack := range stacks {
		for i := 0; i < size; i++ {
			stack.Push(i)
		}
		for i := size - 1; i >= 0; i-- {
			val, err := stack.Pop()
			if val != i {
				t.Errorf("Value popped from %T is %d, but we expected it to be %d", stack, val, i)
			}
			if err != nil {
				t.Errorf(err.Error())
			}
		}
	}
}
```
Definido `size = 10` o que esse teste faz é criar uma lista com dez elementos numerados de 0 até 9

```
[0 1 2 3 4 5 6 7 8 9]
```

Depois, remover elementos do fim dez vezes. Isso por que o loop de remoção irá de `i := 10 - 1` até zero.  Então, o resultado esperado seria

```
Pop() -> [0 1 2 3 4 5 6 7 8] 9 was removed
Pop() -> [0 1 2 3 4 5 6 7] 8 was removed
Pop() -> [0 1 2 3 4 5 6] 7 was removed
...
Pop() -> [0] 1 was removed
Pop() -> [] 0 was removed
```

O teste me retorna um resultado esperado diferente, como é possível ver abaixo

```
=== RUN   TestPop
    stack_test.go:55: Value popped from *helper.LinkedStack is 9, but we expected it to be 8
    stack_test.go:55: Value popped from *helper.LinkedStack is 8, but we expected it to be 7
    stack_test.go:55: Value popped from *helper.LinkedStack is 7, but we expected it to be 6
    stack_test.go:55: Value popped from *helper.LinkedStack is 6, but we expected it to be 5
    stack_test.go:55: Value popped from *helper.LinkedStack is 5, but we expected it to be 4
    stack_test.go:55: Value popped from *helper.LinkedStack is 4, but we expected it to be 3
    stack_test.go:55: Value popped from *helper.LinkedStack is 3, but we expected it to be 2
    stack_test.go:55: Value popped from *helper.LinkedStack is 2, but we expected it to be 1
    stack_test.go:55: Value popped from *helper.LinkedStack is 1, but we expected it to be 0
```

**Comment by eduardolfalcao** [comment]
Oi Raphael

Revendo o código do teste, ele parece estar correto. 
Se o teste está correto, então muito provavelmente a sua implementação da função Pop (ou até mesmo a função Push) é que deve estar errada. O objetivo do teste é esse mesmo: detectar bugs na nossa implementação.

Porém, se você realmente acha que o teste está errado, você poderia me apontar onde está o erro e como corrigi-lo?

**Comment by raphaelramosds** [comment]
Realmente, o código está certo. Eu me enganei ao pensar que a função deveria retornar o elemento removido. Na verdade ela deve retornar o novo último elemento
